name: Build and create zip - IOTA Blog
on:
  push:
    branches:
      - feat/iota-blog
jobs:
  build_create_zip_iota:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
            node-version: '14'
      - name: Install dependencies
        run: cd src && yarn
      - name: add webpack
        run: npm link webpack
      - name: Build and create zip
        run: zip -r liebling.zip ./* -x 'node_modules/*' -x '*src*'
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with: 
          name: IOTA_Blog
          path: liebling.zip
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
